[package]
name = "ffxiv-simbot-cmd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ffxiv-simbot"
path = "src/main.rs"
doc = false

[dependencies.ffxiv-simbot-lib-db]
version = "0.1.0"
path = "../lib/db"

[dependencies.ffxiv-simbot-lib-engine]
version = "0.1.0"
path = "../lib/engine"
